estacao/boletins/urls.py
from django.urls import path

from .views import boletins_index

app_name = 'boletins'

urlpatterns = [
    path('', boletins_index, name='index')
]

estacao/contact/urls.py
from django.urls import path
from estacao.contact.views import contact_index

app_name = 'contact'


urlpatterns = [
    path('', contact_index, name='contact_index')
]

estacao/core/urls.py
from django.urls import path
from estacao.core.views import home

app_name = 'core'


urlpatterns = [
    path('', home, name='home')
]

estacao/instruments/urls.py
from django.urls import path

from .views import instruments_index

app_name = 'instruments'

urlpatterns = [
    path('', instruments_index, name='instruments_index')
]

estacao/museu/urls.py
from django.urls import path
from estacao.museu.views import museu_index


app_name = 'museu'

urlpatterns = [
    path('', museu_index, name='index')
]

estacao/pessoal/urls.py
from django.urls import path
from estacao.pessoal.views import pessoal_index

app_name = 'pessoal'


urlpatterns = [
    path('', pessoal_index, name='pessoal_index')
]

estacao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('estacao.core.urls')),
    path('pessoal/', include('estacao.pessoal.urls')),
    path('contato/', include('estacao.contact.urls')),
    path('instrumentos/', include('estacao.instruments.urls')),
    path('boletins/', include('estacao.boletins.urls')),
    path('museu/', include('estacao.museu.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

estacao/boletins/models.py
from django.db import models
from django.utils.translation import gettext as _

from .managers import BoletinQuerySet


class Boletin(models.Model):
    CATEGORY_CHOICES = (
        ('climatologico', 'Boletim climatológico'),
        ('trimestral', 'Boletim trimestral'),
        ('mensal', 'Boletim mensal'),
        ('tecnico', 'Relatório técnico'),
    )

    title = models.CharField(_("Títlo"), max_length=50)
    category = models.CharField(
        _("Categoria"), max_length=50, choices=CATEGORY_CHOICES)
    file = models.FileField(_("Arquivo"), upload_to='boletins')

    objects = BoletinQuerySet.as_manager()

estacao/contact/models.py
from django.db import models

estacao/instruments/models.py
from django.db import models
from django.utils.translation import gettext as _


class Instruments(models.Model):
    title = models.CharField(_("título"), max_length=50)
    text = models.TextField(_("texto"), max_length=2048)
    image = models.FileField(_("imagem"), upload_to='instruments')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'instrumento'
        verbose_name_plural = 'instrumentos'

estacao/pessoal/models.py
from django.db import models


class TeamModel(models.Model):
    name = models.CharField('nome', max_length=128)
    role = models.CharField('cargo', max_length=128)
    image = models.FileField('imagem', upload_to='team/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

estacao/boletins/views.py
from django.shortcuts import render

from .models import Boletin


def boletins_index(request):
    context = {
        'climatologico': Boletin.objects.climatologico(),
        'trimestral': Boletin.objects.trimestral(),
        'mensal': Boletin.objects.mensal(),
        'tecnico': Boletin.objects.tecnico()
    }
    return render(request, 'boletins.html', context)

estacao/contact/views.py
from django.shortcuts import render


def contact_index(request):
    return render(request, 'contact_index.html')

estacao/core/views.py
from django.shortcuts import render
from bokeh.resources import CDN
from estacao.core.resources import WeatherResource
from estacao.core.charts.temperature import Temperature
from estacao.core.charts.pressao import Pressao


def home(request):
    temp = render_temperature_chart()
    weather_data = get_weather_data()
    pressao = render_pressao_chart()
    context = {
        'conditions': weather_data,
        'temperature': temp,
        'pressao': pressao,
        'bokehcdn': CDN.render()
    }
    return render(request, 'home.html', context)


def get_weather_data():
    weather = WeatherResource()
    weather_data = weather.get_weather_data()
    return weather_data.get('current')


def render_temperature_chart():
    temperature = Temperature()
    temperature.plot()
    return temperature


def render_pressao_chart():
    pressao = Pressao()
    pressao.plot_graph()
    return pressao

estacao/instruments/views.py
from django.shortcuts import render

from estacao.instruments.models import Instruments


def instruments_index(request):
    instruments = Instruments.objects.all()
    context = {'instruments': instruments}
    return render(request, 'instruments.html', context=context)

estacao/museu/views.py
from django.shortcuts import render


def museu_index(request):
    return render(request, 'museu.html')

estacao/pessoal/views.py
from django.shortcuts import render
from estacao.pessoal.models import TeamModel


def pessoal_index(request):
    team = TeamModel.objects.all()
    
    context = {'team': team}
    return render(request, 'pessoal_index.html', context)

estacao/boletins/templates/boletins.html
{% extends 'main.html' %} {% block content %}

<h1>Boletins e Relatórios</h1>
<hr>

<ul class="nav nav-tabs">
  <li class="nav-item" role="presentation">
    <a
      class="nav-link active"
      id="climatologicos-tab"
      data-toggle="tab"
      href="#climatologicos"
      role="tab"
      aria-controls="climatologicos"
      aria-selected="true"
      >Boletins climatológicos</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="trimestrais-tab"
      data-toggle="tab"
      href="#trimestrais"
      role="tab"
      aria-controls="trimestrais"
      aria-selected="true"
      >Boletins trimestrais</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="mensais-tab"
      data-toggle="tab"
      href="#mensais"
      role="tab"
      aria-controls="mensais"
      aria-selected="true"
      >Boletins mensais</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="tecnicos-tab"
      data-toggle="tab"
      href="#tecnicos"
      role="tab"
      aria-controls="tecnicos"
      aria-selected="true"
      >Boletins técnicos</a
    >
  </li>
</ul>

<div class="tab-content">
  <div
    class="tab-pane fade show active"
    id="climatologicos"
    role="tabpanel"
    aria-labelledby="climatologicos-tab"
  >
    <p>
      Desde 1997, a estação meteorológica do IAG/USP elabora anualmente um
      Boletim Climatológico. Em cada boletim é apresentada uma síntese das
      observações meteorológicas, bem como os valores médios observados durante
      o ano. Para maiores detalhes sobre os dados, análises e ou consultas,
      envie um e-mail para estacao@model.iag.usp.br
    </p>
    <p>
      Os seguintes Boletins Climatológicos da Estação Meteorológica do IAG estão
      disponibilizados em formato PDF:
    </p>

    <p>Boletins Climatológicos</p>
    <ul class>
      {% for boletin in climatologico %}
      <li>{{ boletin.title }}: {{ boletin.file }}</li>
      {% endfor %}
    </ul>
  </div>
  <div
    class="tab-pane fade show active"
    id="trimestrais"
    role="tabpanel"
    aria-labelledby="trimestrais-tab"
  >
    <p>Boletins trimestrais</p>

    <ul>
      {% for boletin in trimestral %}
      <li>{{ boletin.title }}: {{ boletin.file }}</li>
      {% endfor %}
    </ul>
  </div>
  <div
    class="tab-pane fade show active"
    id="mensais"
    role="tabpanel"
    aria-labelledby="mensais-tab"
  >
    <p>Boletins mensais</p>

    <ul>
      {% for boletin in mensal %}
      <li>{{ boletin.title }}: {{ boletin.file }}</li>
      {% endfor %}
    </ul>
  </div>
  <div
    class="tab-pane fade show active"
    id="tecnicos"
    role="tabpanel"
    aria-labelledby="tecnicos-tab"
  >
    <p>Boletins técnico</p>

    <ul>
      {% for boletin in tecnico %}
      <li>{{ boletin.title }}: {{ boletin.file }}</li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock content %}

estacao/contact/templates/address.html
<iframe width="600" height="450" frameborder="0" style="border:0"
src="https://www.google.com/maps/embed/v1/place?q=avenida%20miguel%20stefano%204200&key=..." allowfullscreen></iframe>

estacao/contact/templates/contact_index.html
{% extends 'main.html' %}
{% load i18n %}

{% block content %}

    <div class="row">
        <p class="title h2">{% trans 'Informações para contato' %}</p>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{% trans "Informações Gerais" %}</h5>
                    <h6 class="card-subtitle text-muted mb-4">Vistas e solicitação de dados</h6>
                    <div class="card-text">
                        {% include 'general_info.html' %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{% trans "Telefone/Fax" %}</h5>
                    <div class="card-text">
                        {% include 'phone.html' %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{% trans "Endereço" %}</h5>
                    <h6 class="text-muted">
                        Parque de Ciência e Tecnologia da USP
                    </h6>
                    <h6 class="text-muted">
                        Av Miguel Stéfano, No.4200, Água Funda - São Paulo
                    </h6>
                    <h6 class="text-muted">
                        CEP 04301-904 - Brasil
                    </h6>
                    <div class="card-text">
                        {% include 'address.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

estacao/contact/templates/general_info.html
<ul class="list-group">
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fas fa-envelope"></i>
        </div>
         estacao.aca@iag.usp.br
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fab fa-twitter-square"></i>
        </div>
         @estacao_IAG
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fab fa-facebook-square"></i>
        </div>
         Estação Meteorológica do IAG-USP
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fab fa-scribd"></i>
        </div>
         /estacao_IAG
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fab fa-flickr"></i>
        </div>
         estacao_IAG
    </li>
</ul>

estacao/contact/templates/phone.html
<ul class="list-group">
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fas fa-phone"></i>
        </div>
        (0xx11) 5077-6344
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fas fa-phone"></i>
        </div>
        (0xx11) 5077-6315
    </li>
    <li class="list-group-item">
        <div class="btn btn-primary">
            <i class="fas fa-phone"></i>
        </div>
        (0xx11) 5077-6332 (Museu de Meteorologia)
    </li>
</ul>

estacao/core/templates/current_conditions.html
{% load i18n %}

<ul class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Temperatura do Ar' %}</small>
        <span class="badge badge-primary badge-pill">{{ conditions.temperatura_ar }}ºC</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Temperatura do Ponto de Orvalho' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.temperatura_ponto_orvalho }}ºC</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'UR' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.umidade_relativa }}</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Temperatura Mínima' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.temperatura_min }}ºC</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Temperatura Máxima' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.temperatura_max }}ºC</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Vento' %}</small>
        <small class="badge badge-primary badge-pill">
            {% if conditions.dir == 'C' %}
                Calmo
            {% else %}
                {{ conditions.vento }} m/s de {{ conditions.dir }}
            {% endif %}
        </small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Pressão' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.pressao }} hPa</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Visibilidade Horizontal' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.visibilidade }}</small>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Nuvens Baixas' %}</small>
        {% if conditions.nuvens_baixas %}
            <small class="badge badge-primary badge-pill">
                {{ conditions.nuvens_baixas }} - {{ conditions.quant_nuvens_baixas }}/10
            </small>
        {% endif %}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Nuvens Médias' %}</small>
        {% if conditions.nuvens_medias %}
            <small class="badge badge-primary badge-pill">
                {{ conditions.nuvens_medias }} - {{ conditions.quant_nuvens_medias }}/10
            </small>
        {% endif %}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Nuvens Altas' %}</small>
        {% if conditions.nuvens_altas %}
            <small class="badge badge-primary badge-pill">
                {{ conditions.nuvens_altas }} - {{ conditions.quant_nuvens_altas }}/10
            </small>
        {% endif %}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <small>{% trans 'Fenômenos Diversos' %}</small>
        <small class="badge badge-primary badge-pill">{{ conditions.diversos }}</small>
    </li>
</ul>

estacao/core/templates/home.html
{% extends 'main.html' %}
{% load i18n %}

{% block scripts %}
    {{ bokehcdn|safe }}
    {{ temperature.get_scripts|safe }}
    {{ pressao.get_scripts|safe }}
{% endblock scripts %}


{% block header %}
    <!-- Header -->
    <header class="bg-primary py-5 mb-5">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-lg-12">
                    <h1 class="display-4 text-white mt-5 mb-2">{% trans 'Estação Meteorológica' %}</h1>
                    <h3 class="lead text-white-50">{% trans 'Seção Técnica de Serviços Meteorológicos' %}</h3>
                    <h3 class="lead mb-5 text-white-50">{% trans 'Instituto de Astronomia, Geofísica e Ciências Atmosféricas' %}</h3>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
<div class="row">
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <img src="https://i.picsum.photos/id/1056/700/250.jpg" alt="" class="card-img">
            <div class="card-img-overlay">
                <h5 class="card-title text-light">{% trans 'Condições Atuais' %} {{ conditions.data }}<h5>
              
                <p class="h2 text-light">{{ conditions.temperatura_ar }}ºC - {{ conditions.ur }}%</p>
            </div>
            <div class="card-body">
                <div class="card-text">{% include 'current_conditions.html' %}</div>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Meteograma' %}</h5>
                <div class="p-5">
                    {{ temperature.get_div|safe }}
                    {{ pressao.get_div|safe }}
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Boletins e Relatórios' %}</h5>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Museu de Meteorologia' %}</h5>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Solicitação de Dados' %}</h5>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Explorando a Meteorologia' %}</h5>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{% trans 'Cursos' %}</h5>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

estacao/core/templates/main.html
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <title>Estação Meteorológica</title>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'boletins:index' %}">Boletins e Relatórios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'museu:index' %}">Museu Meteorológico</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'instruments:instruments_index' %}" class="nav-link">{% trans 'Instrumentos' %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">{% trans 'Contato e Localização' %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'pessoal:pessoal_index' %}" class="nav-link">{% trans 'Pessoal' %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}
    {% endblock header %}

    <!-- Page Content -->
    <div class="container-fluid">
        
        {% block content %}
        {% endblock content %}

        {% block scripts %}
        {% endblock scripts %} 
    </div>
</body>
</html>

estacao/instruments/templates/instruments.html
{% extends 'main.html' %} 

{% block content %}

    <h1>Instrumentos</h1>

    <div class="container-fluid">
    
        <p>
            Nesta página estão descritas de forma resumida às técnicas adotadas pela 
            Estação Meteorológica do IAG/USP para as observações de superfície, bem 
            como a época de sua implantação. Detalhes (por menores) sobre o início das 
            atividades da Estação Meteorológica em 1932 e procedimentos empregados até 
            inícios dos anos 1960 podem ser encontrados em Santos (1964). Informações 
            mais detalhadas sobre a instrumentação empregada e sobre os procedimentos 
            de observação e da interpretação dos dados podem ser obtidas nas publicações da 
            Organização Meteorológica Mundial (WMO, 1994; WMO, 1996).
        </p>
        <p>
            As medidas da Estação Meteorológica tiveram início em 1933 a partir de 
            observações horárias realizadas entre 7 e 10 horas e das 12 às 15 horas. 
            Em março e julho do mesmo ano, foram incorporadas as observações das 21 e 24 
            horas respectivamente. Entre janeiro de 1935 e outubro de 1945, as 
            observações foram realizadas das 7 às 22 horas. A partir deste período até agosto 
            de 1948, as observações permaneceram das 7 às 14 horas e às 21 horas. 
            Posteriormente até dezembro de 1949, as observações voltaram a ser realizadas 
            entre o período das 7 às 22 horas. Finalmente, a partir de janeiro de 1950, 
            as observações meteorológicas passaram a ser realizadas ininterruptamente a 
            cada hora entre 7 e 24 horas, todos os dias do ano. A Tabela 1 apresenta 
            detalhes sobre o período de implementação dos instrumentos e das observações 
            da Estação Meteorológica do IAG/USP, enquanto que a Tabela 2 apresenta o ano da 
            implementação e descrição dos instrumentos instalados.
        </p>
        <p>
            Os instrumentos mecânicos automáticos (anemógrafo, barógrafo, termógrafo, higrógrafo, 
            pluviógrafo e actinógrafo) registram as informações continuamente durante às 24 
            horas do dia. A partir de 2009, às observações coletadas pelos observadores meteorológicos
             e as registradas pelos instrumentos automáticos, são arquivadas digitalmente em 
             planilhas eletrônicas que são instantaneamente transferidas para o banco 
             de dados e o portal da internet [http://www.estacao.iag.usp.br]. No dia seguinte às 
             observações, as informações coletadas são confirmadas a partir da verificação da 
             folha de observação e dos registradores automáticos e suas medições, sendo que da 
             1 às 6 horas são inseridas nas folhas de observações.
        <p>
            É importante ressaltar que a Estação Meteorológica não adota o horário de verão e 
            utiliza o tempo universal coordenado (TMC) ou tempo médio de Greenwich (TMG) menos 3 
            horas, durante o ano inteiro.    
        </p>
    </div>


    {% for instrument in instruments %} 
        <div class="media mb-4">
            <img src="{{ instrument.image.url }}" width="200" heigh="200" class="img-thumbnail mr-4">
            <div class="media-body">
                <h5 class="mt-0"><strong>{{ instrument.title }}</strong></h5>
                {{ instrument.text }}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

estacao/pessoal/templates/pessoal_index.html
{% extends 'main.html' %}
{% load i18n %}

{% block content %}
    <div class="row">
        <p class="title h2">{% trans 'Pessoal' %}</p>
    </div>
    
    <div class="row">
        {% for person in team %}
        <div class="col-md-3 col-sm-6 card-row-deck">
            <div class="card mb-4 shadow">
                <img src="{{ person.image.url }}" alt="{{ person.name }} image" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ person.name }}</h5>
                    <small class="text-muted">{{ person.role }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}